const lifestyleImages = [
    {id: 1,
        src: '/img/lifestyle1.png', 
        alt: 'Lifestyle Image 1',
        description: 'Enjoying skincare in a serene environment.',
      },
      {
        id: 2,
        src: '/img/lifestyle2.png',
        alt: 'Lifestyle Image 2',
        description: 'Natural beauty routine with Afrigem products.',
      },
      {
        id: 3,
        src: '/img/lifestyle3.png',
        alt: 'Lifestyle Image 3',
        description: 'Embracing self-care moments.',
      },
    {id: 4,
        src: '/img/lifestyle4.png',
        alt: 'Lifestyle Image 4',
        description: 'Radiate confidence with your skincare routine while enjoying a refreshing morning.',
      },
      {
        id: 5,
        src: '/img/lifestyle5.png',
        alt: 'Lifestyle Image 5',
        description: 'Experience the power of nature with our organic ingredients, perfect for every skin type.',
      },
      {
        id: 6,
        src: '/img/lifestyle6.png',
        alt: 'Lifestyle Image 6',
        description: 'Indulge in a moment of relaxation with our calming facial masks.',
      },
      {
        id: 7,
        src: '/img/lifestyle7.png',
        alt: 'Lifestyle Image 7',
        description: 'Elevate your self-care rituals with Afrigem Beauty products, designed for modern lifestyles.',
      },
      {
        id: 8,
        src: '/img/lifestyle8.png',
        alt: 'Lifestyle Image 8',
        description: 'Capture the essence of beauty in everyday moments with our nourishing skincare line.',
      },
      {
        id: 9,
        src: '/img/lifestyle9.png',
        alt: 'Lifestyle Image 9',
        description: 'Show off your glow with our brightening serums, perfect for a radiant complexion.',
      },
      {
        id: 10,
        src: '/img/lifestyle10.png',
        alt: 'Lifestyle Image 10',
        description: 'Celebrate beauty in diversity with our inclusive range of skincare products.',
      },
      {
        id: 11,
        src: '/img/lifestyle11.png',
        alt: 'Lifestyle Image 11',
        description: 'Transform your skincare routine into a luxurious experience with Afrigem Beauty.',
      },
      {
        id: 12,
        src: '/img/lifestyle12.png',
        alt: 'Lifestyle Image 12',
        description: 'Embrace the beauty of self-love and care with our premium product range.',
      },
      {
        id: 13,
        src: '/img/lifestyle13.png',
        alt: 'Lifestyle Image 13',
        description: 'Let your natural beauty shine through with our gentle and effective formulations.',
      },
      {
        id: 14,
        src: '/img/lifestyle14.png',
        alt: 'Lifestyle Image 14',
        description: 'Enjoy moments of tranquility with our soothing skincare solutions.',
      },
      {
        id: 15,
        src: '/img/lifestyle15.png',
        alt: 'Lifestyle Image 15',
        description: 'Refresh your routine with our revitalizing products, perfect for a pick-me-up.',
      },
      {
        id: 16,
        src: '/img/lifestyle16.png',
        alt: 'Lifestyle Image 16',
        description: 'Cultivate a glowing complexion with our targeted treatments.',
      },
      {
        id: 17,
        src: '/img/lifestyle17.png',
        alt: 'Lifestyle Image 17',
        description: 'Incorporate mindfulness into your beauty regimen with our holistic approach.',
      },
      {
        id: 18,
        src: '/img/lifestyle18.png',
        alt: 'Lifestyle Image 18',
        description: 'Celebrate your unique beauty journey with our personalized skincare solutions.',
      },
      {
        id: 19,
        src: '/img/lifestyle19.png',
        alt: 'Lifestyle Image 19',
        description: 'Revitalize your skin and spirit with our energizing products.',
      },
      {
        id: 20,
        src: '/img/lifestyle20.png',
        alt: 'Lifestyle Image 20',
        description: 'Cherish self-care moments and prioritize your well-being with Afrigem Beauty.',
      },
      {
        id: 21,
        src: '/img/lifestyle21.png',
        alt: 'Lifestyle Image 21',
        description: 'Elevate your skincare experience and embrace the art of beauty rituals.',
      },
    ];
